apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hw-1
  name: hw-1
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hw-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hw-1
    spec:
      containers:
        - env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: hw-1-config-sojq
          image: gcr.io/ticket-idm/github.com/iliadmitriev/hw
          imagePullPolicy: IfNotPresent
          name: helloworld-sha256-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: hw-1
  name: hw-1-hpa-ao39
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hw-1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hw-1
  name: hw-1-service
  namespace: default
spec:
  clusterIP: None
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 8080
  selector:
    app: hw-1
